site_name: K8S Anomaly Detection Operator
repo_name: amitde69/anomaly-operator
repo_url: https://github.com/amitde69/anomaly-operator
edit_uri: edit/main/docs/
strict: true
# dev_addr: 10.0.0.14:8080

nav:
  - Home:
    - Welcome: index.md
  - Getting Started:
    - Operator Deployment: getting_started/operator_deployment.md
    - Detector CRD:
      - Configuration: getting_started/configurations.md
    - Logs: getting_started/upgrade/logs.md
    - Metrics: getting_started/upgrade/metrics.md
  - Deployment: deployment.md
  #   - gRPCServer: examples/grpc_server.md
  #   - Setup External DNS: guide/integrations/external_dns.md
  #   - RBAC to access OIDC Secret: examples/secrets_access.md



plugins:
  - search
  # - git-revision-date-localized:
  #     enable_creation_date: true
theme:
  name: material
  language: en
  favicon: assets/images/anomaly-detection.svg
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
  custom_dir: docs/theme_overrides
# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra_css:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
extra_javascript:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js  