apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "appname" .}}
  namespace: default
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.account }}:role/{{ .Values.cluster_name }}-xx-role