apiVersion: monitoring.amitdebachar/v1alpha1
kind: Detector
metadata:
  name: minimal-detector
spec:
  image: "amitde7896/anomaly-operator:latest-detector"
  prom_url: "http://prometheus.monitoring.svc.cluster.local"
  interval_mins: "15"
  queries:
  - name: "sum_pods_running_anomaly"
    query: 'sum(kube_pod_status_phase{phase=~"Running", pod=~"application-pod-.*"}) > 1'
    train_window: "14d"
---
apiVersion: v1
kind: Service
metadata:
  name: minimal-detector
spec:
  ports:
    - port: 9099
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app: minimal-detector
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minimal-detector-sm
  labels:
    prometheus: anomaly-detector
spec:
  selector:
    matchLabels:
      app: minimal-detector
  endpoints:
  - port: metrics
    interval: "30s"
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: thanos-ruler
  name: minimal-detector
spec:
  groups:
  - name: minimal-detector-alerts
    rules:
    - alert: AnomalyDetected
      annotations:
        description: 'detector {{ $labels.name }} Found anomalies.'
      expr: anomaly_counter > 0
      for: 1m