apiVersion: monitoring.amitdebachar/v1alpha1
kind: Detector
metadata:
  name: minimal-detector
spec:

  ## (required) The detector image
  image: "amitde7896/anomaly-operator:latest-detector"

  ## (required) Promethus HTTP API endpoint 
  prom_url: "http://prometheus.monitoring.svc.cluster.local"

  ## (required) Evaluation interval in minutes in which the Detector
  ## will query Prometheus and analyze for anomalies
  ## Note: use float for under 1 min interval e.g. "0.01"  
  interval_mins: "15"

  ## (required) List of PromQL expressions which the detector 
  ## will query and evaluate using the configured Prometheus endpoint and interval   
  queries:

    ## (required) Query name which will appear in the logs and metrics 
    ## in order to correlate the detected anomaly to the configured query  
  - name: "sum_pods_running_anomaly"

    ## (required) Query PromQL expression
    query: 'sum(kube_pod_status_phase{phase=~"Running", pod=~"application-pod-.*"}) > 1'

    ## (required) parse_datetime formated text such as - "1m" "4h" "2d" "3w"
    ## Past period for which the detector will train and learn the trend
    ## Note: bigger value means longer query time
    train_window: "14d"
