apiVersion: monitoring.amitdebachar/v1alpha1
kind: Detector
metadata:
  labels:
    app.kubernetes.io/name: detector
    app.kubernetes.io/instance: detector-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: detector-sample
spec:
  image: "xxxx/master/anomaly-operator:0.0.2"
  prom_url: "https://prometheus.example.com"
  interval_mins: "0.001"
  queries:
  - name: "microservice_backend_scale"
    query: 'sum(kube_pod_labels{label_app=~"ms-.*"}) by (label_app) >= 10'
    train_window: "1d"
    # flexibility: "5"
    # resolution: 200
    # buffer_pct: 150
  - name: "microservice_backend_scale_2"
    query: 'sum(kube_pod_labels{label_app=~"ms-.*"}) by (label_app) >= 10'
    detection_window_hours: 1
    train_window: "1d"
    # flexibility: "5"
    resolution: 200
    # buffer_pct: 150
  - name: "microservice_backend_scale_3"
    query: 'sum(kube_pod_labels{label_app=~"ms-.*"}) by (label_app) >= 10'
    train_window: "1d"
    # flexibility: "5"
    # resolution: 200
    buffer_pct: 100
  - name: "microservice_backend_scale_4"
    query: 'sum(kube_pod_labels{label_app=~"ms-.*"}) by (label_app) >= 10'
    train_window: "1d"
    flexibility: "0.05"
    # resolution: 200
    # buffer_pct: 150
